build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: roster # don't change
jar_name: klortz-roster # set this to '<first_initial><lastname>-roster' ex: sgreenberg-roster

github_app_repo_uri: https://github.com/klortz/roster-gradle.git # https url of your roster app github fork.  ex: https://github.com/spgreenberg/roster-initial.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/klortz/training-pipelines-initial.git # https url of your training-pipelines-initial fork.  ex: https://github.com/spgreenberg/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: klortz-roster-version # set to '<first_initial><lastname>-roster-version'.  ex: sgreenberg-roster-version
initial_version: 0.0.1

artifact_regexp: klortz-roster-(.*).jar # set to '<first_initial><lastname>-roster-(.*).jar'.  ex: sgreenberg-roster-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: api.run.pivotal.io # set to cf api endpoint
cf_dev_organization: rscale-training-2 # set to your org
cf_dev_space: kirk.lortz@cgi.com # set to your space
cf_dev_hostname: roster-klortz # set to 'roster-<first_initial><lastname>'. ex: roster-sgreenberg
cf_dev_domain: cfapps.io # set to the apps domain for your CF
cf_dev_manifest: # set to the dev manifest path in your roster app repository. ex: dev-manifest.yml
